version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    container_name: db
  challenge-labs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: challenge-labs
    image: challenge-labs-image
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: agendamento