version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  challenge-labs:
    build: .
    container_name: challenge-labs
    image: challenge-labs-image
    ports:
      - 9999:9999
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: agendamento