version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gmcore123
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: agendamento