server:
  port: 9999
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: agendamento
logging:
  level:
    com.challenge.labs: debug